name = "IGORY"
author = "ME&KO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43263d74a1ec4245b7154c60f6e57aaa4091dc94df133485cd5ef0f88caf6f98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
