name = "IGORY"
author = "ME&KO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1473ea00c622a411bcbea9872aa7fc0f897d4e7394cefe096f75f8af85f6c7e8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
