#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 26 22:32:08 MSK 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=
